name: Run Tests Using Built Image

on:
  workflow_run:
    workflows: ["Build and Push Image"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/oppt:${{ github.sha }}

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Normalize image name
        run: echo "IMAGE_NAME_LOWER=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Pull Docker image
        run: docker pull ${{ env.IMAGE_NAME_LOWER }}

      - name: Run Python Test inside Container
        run: |
          docker run --rm ${{ env.IMAGE_NAME_LOWER }} \
            bash -c "cd /app && pip install . && python -c 'import oppt_py'"
